### ISSUE TITLE
favicon-problem

### ISSUE THREAD

**Issue by Kissa0330** [Yuya-bakuretsu/DisPlay#24]
jsからsvgデータをサーバーに保存して動的に変更したいので、サーバーに保存する方法の考案/実装をお願いします！

**Comment by Yuya-bakuretsu** [comment]
https://blog.katsubemakito.net/html5/canvas-sendserver
↑キャンバスに描画した画像もといsvgのデータをサーバーに送信する方法の参考
サーバーに送るという手前サーバーサイドで実装するのかと思ったらフロントエンドでやるやつでした。まぁボタン押したのにサーバーサイドは反応できないからね。仕方ないね。
